print("선호하는 위스키를 입력해주세요: Wild Turkey American Spirit 15 year old, The Balvenie 17 year old, Lagavulin 30 year old")
print("가격의 범위를 입력해주세요($): 50, 1000")
print("점수의 범위를 입력해주세요(0~100): 85, 100")
print("=================================================================")
print("==========================위스키 추천결과===========================")
print("=================================================================")
print("1. Lagavulin 12 year old (Diageo Special Releases 2009) / 점수 : 90 / 가격 : 75")
print("2. Wild Turkey Wild Turkey 'Tradition' 14 year old / 점수 : 89 / 가격 : 100")
print("3. Mortlach, 1997 vintage / 점수 : 85 / 가격 : 406")
print("4. Talisker 30 year old / 점수 : 90 / 가격 : 349")
print("5. The Macallan Sienna / 점수 : 88 / 가격 : 103")
